import { Vehicle, Testimonial, ServiceItem, Driver } from '@/types';

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    name: 'Toyota Land Cruiser Prado TX-L',
    categoryName: 'SUVs',
    categoryId: 'cat-suv',
    image: '/images/suv_prado_2.jpg',
    pricePerDay: 85000,
    passengers: 7,
    luggage: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    features: ['Chauffeur Included', 'Climate Control AC', 'Full Tint', 'VIP Escort Ready', 'Bluetooth System'],
    description: 'Executive 4WD Toyota Land Cruiser Prado SUV for luxury airport transfers, VIP delegations, and intercity travel across Imo State and South-East Nigeria.',
    isAvailable: true,
  },
  {
    id: 'v2',
    name: 'Toyota Camry Executive Sedan',
    categoryName: 'Executive Cars',
    categoryId: 'cat-exec',
    image: '/images/car_sedan.jpg',
    pricePerDay: 45000,
    passengers: 4,
    luggage: 3,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    features: ['Chauffeur Included', 'Cold AC', 'Leather Interior', 'Smooth Ride', 'Fuel Efficient'],
    description: 'Comfortable executive sedan for business travel, hotel transfers, and daily town trips within Owerri.',
    isAvailable: true,
  },
  {
    id: 'v3',
    name: 'Toyota Prado VIP Luxury SUV',
    categoryName: 'Luxury Vehicles',
    categoryId: 'cat-lux',
    image: '/images/suv_prado_1.jpg',
    pricePerDay: 150000,
    passengers: 7,
    luggage: 6,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    features: ['Executive Chauffeur', 'V8 Power', 'Premium Sound', 'High Security', 'Luxury Interior'],
    description: 'Flagship luxury SUV for VIP dignitary arrivals, weddings, and high-security executive movement.',
    isAvailable: true,
  },
  {
    id: 'v4',
    name: 'Executive Fleet SUV Prado TX',
    categoryName: 'SUVs',
    categoryId: 'cat-suv',
    image: '/images/suv_prado_3.webp',
    pricePerDay: 95000,
    passengers: 7,
    luggage: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    features: ['Dedicated Driver', 'Dual AC Units', 'High Roof Comfort', 'Reclining Seats', 'Luggage Space'],
    description: 'Spacious executive SUV for corporate team transportation, wedding guests, and group airport movement.',
    isAvailable: true,
  },
  {
    id: 'v5',
    name: 'Toyota Executive Sedan Special',
    categoryName: 'Executive Cars',
    categoryId: 'cat-exec',
    image: '/images/images (4).jpg',
    pricePerDay: 110000,
    passengers: 4,
    luggage: 3,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    features: ['Professional Chauffeur', 'Climate Control', 'Leather Seats', 'Tinted Windows', 'Executive Prestige'],
    description: 'Prestigious luxury sedan for corporate executives, VIP events, and high-profile visits to Owerri.',
    isAvailable: true,
  },
  {
    id: 'v6',
    name: 'Toyota Corolla Comfort',
    categoryName: 'Economy Cars',
    categoryId: 'cat-econ',
    image: '/images/images (10).jpg',
    pricePerDay: 35000,
    passengers: 4,
    luggage: 2,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    features: ['Experienced Driver', 'Air Conditioning', 'Fuel Efficient', 'Clean Interior'],
    description: 'Reliable and affordable daily car hire for city errands and quick transfers around Owerri town.',
    isAvailable: true,
  },
];

export const MOCK_CATEGORIES = [
  { id: 'cat-suv', name: 'SUVs', icon: 'Car' },
  { id: 'cat-exec', name: 'Executive Cars', icon: 'ShieldCheck' },
  { id: 'cat-lux', name: 'Luxury Vehicles', icon: 'Crown' },
  { id: 'cat-bus', name: 'Mini Bus', icon: 'Users' },
  { id: 'cat-econ', name: 'Economy Cars', icon: 'Zap' },
];

export const MOCK_ADDONS = [
  { id: 'add-mopol', name: 'Armed Mobile Police (MOPOL) Escort', price: 45000, perDay: true, description: 'Dedicated MOPOL escort vehicle and armed personnel for VIP security.' },
  { id: 'add-vip', name: 'Sam Mbakwe Airport VIP tarmac greeting', price: 20000, perDay: false, description: 'Personalized tarmac greeting and assistance at Sam Mbakwe Airport.' },
  { id: 'add-seat', name: 'Child Safety Seat', price: 5000, perDay: true, description: 'Clean, ISOFIX-certified child safety seat for infants or toddlers.' },
  { id: 'add-fuel', name: 'Prepaid Fuel Tank', price: 35000, perDay: false, description: 'Full tank of fuel preloaded so you do not need to refuel before returning.' },
];

export const MOCK_BOOKINGS: any[] = [
  {
    id: 'BK-1001',
    referenceCode: 'CJ-98421',
    serviceType: 'Airport Transfer',
    customerName: 'Chinedu Okeke',
    customerEmail: 'chinedu@example.com',
    customerPhone: '+234 803 123 4567',
    vehicleId: 'v1',
    vehicleName: 'Toyota Land Cruiser Prado TX-L',
    vehicleImage: '/images/images (5).jpg',
    pickupLocation: 'Sam Mbakwe International Cargo Airport (QOW)',
    dropoffLocation: 'Protea Hotel, Owerri',
    pickupDate: '2026-08-05',
    pickupTime: '14:30',
    status: 'Confirmed',
    totalAmount: 170000,
    estimatedPrice: 170000,
    addons: [],
    createdAt: '2026-08-01',
  },
  {
    id: 'BK-1002',
    referenceCode: 'CJ-77194',
    serviceType: 'Car Hire',
    customerName: 'Adanna Kalu',
    customerEmail: 'adanna@example.com',
    customerPhone: '+234 806 987 6543',
    vehicleId: 'v3',
    vehicleName: 'Lexus LX570 Luxury SUV',
    vehicleImage: '/images/lexus_lx570_luxury_suv_1785727587647.png',
    pickupLocation: 'Concorde Hotel, Owerri',
    dropoffLocation: 'Enugu City Center',
    pickupDate: '2026-08-08',
    pickupTime: '09:00',
    status: 'Pending',
    totalAmount: 300000,
    estimatedPrice: 300000,
    addons: [],
    createdAt: '2026-08-02',
  },
];

export const MOCK_FAQS = [
  {
    id: 'faq-1',
    question: 'Are all ChimJoy car hires chauffeur-driven?',
    answer: 'Yes. Every vehicle hire includes a professional, vetted driver who understands Owerri routes and traffic patterns.',
  },
  {
    id: 'faq-2',
    question: 'How do airport pickups at Sam Mbakwe Airport work?',
    answer: 'Your driver monitors your flight status and will be waiting at the arrival terminal with a personalized greeting board.',
  },
  {
    id: 'faq-3',
    question: 'Can I request armed MOPOL police escorts?',
    answer: 'Yes. Armed Mobile Police escorts are available as an add-on service for VIP arrivals and interstate road movement.',
  },
  {
    id: 'faq-4',
    question: 'What is the booking cancellation policy?',
    answer: 'Free cancellation up to 24 hours before your scheduled pickup time with 100% refund.',
  },
];

export const MOCK_PARTNERS = [
  { id: 'p1', name: 'Sam Mbakwe Airport QOW', logo: '✈' },
  { id: 'p2', name: 'Protea Hotel Owerri', logo: '🏨' },
  { id: 'p3', name: 'Imo Concorde Hotel', logo: '⭐' },
  { id: 'p4', name: 'FUT Owerri Executive', logo: '🏛' },
  { id: 'p5', name: 'South-East Logistics Network', logo: '🚚' },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Chinedu A.',
    role: 'Business Consultant',
    location: 'Abuja',
    rating: 5,
    content: 'Excellent service from the airport to my hotel. The driver arrived before my flight landed and the vehicle was spotless.',
  },
  {
    id: 't2',
    name: 'Adanna K.',
    role: 'Event Manager',
    location: 'Port Harcourt',
    rating: 5,
    content: 'We hired two SUVs for our family event in Owerri. The drivers were punctual, polite, and knew the roads very well.',
  },
  {
    id: 't3',
    name: 'Emeka O.',
    role: 'Corporate Executive',
    location: 'Lagos',
    rating: 5,
    content: 'ChimJoy provides reliable corporate car hire for our visiting executives. Always professional and on time.',
  },
];

export const MOCK_SERVICES: ServiceItem[] = [
  {
    id: 's1',
    title: 'Airport Pickup & Dropoff',
    description: 'Sam Mbakwe International Cargo Airport (QOW) transfers.',
    image: '/images/images (12).jpg',
  },
  {
    id: 's2',
    title: 'Executive Chauffeur Ride',
    description: 'Chauffeur-driven luxury sedans and SUVs.',
    image: '/images/nigerian_lady_and_driver_1785727555097.png',
  },
  {
    id: 's3',
    title: 'Daily & Intercity Car Hire',
    description: 'Vehicles for intra-state and inter-state movement.',
    image: '/images/images (5).jpg',
  },
  {
    id: 's4',
    title: 'Freight & Logistics Services',
    description: 'Business deliveries and document dispatch in Owerri.',
    image: '/images/nigeria_logistics_dispatch_van_1785727668023.png',
  },
];
